config/routes.rb
Rails.application.routes.draw do

  root to: "public/homes#top"

  scope module: :public do
   resources :items, only: [:index, :show]
    resource :customers, only: [:edit, :update]
    get "customers/my_page" => "customers#show", as: "customers/show"
    get "customers/confirm_withdraw" => "customers#confirm_withdraw"
    patch "customers/withdraw" => "customers#withdraw"
    delete "cart_items/dastroy_all" => "cart_items#destroy_all"
    resources :cart_items, only: [:create, :index, :update]
    post "orders/confirm" => "orders#confirm"
    get "orders/complete" => "orders#complete"
    resources :orders, only: [:new, :create, :index, :show]
    resources :addresses, only: [:new, :create, :edit, :update, :index]
    resources :genres, only: [:show]
    get '/about' => "homes#about", as: "homes/about"
  end

  namespace :admin do
    get "/" => "homes#top", as: "homes/top"
    resources :items, only: [:new, :create, :edit, :update, :index, :show]
    resources :customers, only: [:index, :show, :edit ,:update]
    resources :orders, only: [:show]
    resources :genres, only: [:new, :create, :edit, :update, :index, :show]
  end

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
  }
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  def address_display
    '〒' + shipping_postal_code + ' ' + shipping_address + ' ' + shipping_name
  end

  validates :shipping_postal_code, presence: true
  validates :shipping_address, presence: true
  validates :shipping_name, presence: true
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item

  def subtotal
    item.with_tax_price * amount
  end

  validates :amount, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :email, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true

  enum is_active: { '有効': true, '退会': false }
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy

  validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  belongs_to :genre

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/default-image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end

  def with_tax_price
    (price*1.1).floor
  end

  validates :name, presence: true
  validates :introduction, presence: true
  validates :image, presence: true
  validates :price, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details, dependent: :destroy
  belongs_to :customer
  enum payment_method: { credit_card: 0, transfer: 1 }

  validates :payment_method, presence: true
  validates :shipping_postal_code, presence: true
  validates :shipping_address, presence: true
  validates :shipping_name, presence: true
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :item
  belongs_to :order
  def with_tax_price
    (price*1.1).floor
  end

  def subtotal
    item.with_tax_price * amount
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    customer = Customer.find(params[:id])
      if customer.update(customer_params)
         redirect_to admin_customer_path(customer.id)
      else
        @customer = Customer.find(params[:id])
        render :edit
      end
  end

  private

  def customer_params
    params.require(:customer).permit(:first_name, :last_name, :first_name_kana, :last_name_kana, :postal_code, :address, :telephone_number, :is_active, :email)
  end

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

  def create
    genre = Genre.new(genre_params)
    if genre.save
       redirect_to '/admin/genres'
    else
      render :index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    genre = Genre.find(params[:id])
    if genre.update(genre_params)
       redirect_to admin_genres_path
    else
      @genre = Genre.find(params[:id])
      render :edit
    end
  end

  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.page(params[:page]).per(10)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.page(params[:page]).per(10)
  end

  def new
    @item = Item.new
  end

  def create
    item = Item.new(item_params)
    if item.save
       redirect_to admin_item_path(item.id)
    else
      @item = Item.new
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    item = Item.find(params[:id])
    if item.update(item_params)
       redirect_to admin_item_path(item.id)
    else
      @item = Item.find(params[:id])
      render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:image, :name, :introduction,:genre_id, :price)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details.all
    @total = @order_details.inject(0) { |sum, order_detail| sum + order_detail.subtotal}
    @amount_bill = @total + "800".to_i
  end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  private
def after_sign_in_path_for(resource_or_scope)
    if resource_or_scope.is_a?(Admin)
        admin_homes_top_path
    else
        root_path
    end
end

def
after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :user
        root_path
    elsif resource_or_scope == :admin
        new_admin_session_path
    else
        root_path
    end
end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <div class="row">
    <h4 class="bg-light px-3 my-3"><%= @customer.first_name %><%= @customer.last_name %>さんの会員情報編集</h4>
  </div>
  <div class="form-group row">
    <label class="col-3 col-form-label">会員ID</label>
    <div class="col-4"><%= @customer.id %></div>
  </div>
  <%= form_with model: [:admin ,@customer] do |f| %>
  <div class="form-group row">
    <label class="col-3 col-form-label">氏名</label>
    <div class="col">
      <%= f.text_field :first_name, class: "form-control" %>
    </div>
    <div class="col">
      <%= f.text_field :last_name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group row">
    <label class="col-3 col-form-label">フリガナ</label>
    <div class="col">
      <%= f.text_field :first_name_kana, class: "form-control" %>
    </div>
    <div class="col">
      <%= f.text_field :last_name_kana, class: "form-control" %>
    </div>
  </div>
  <div class="form-group row">
    <label class="col-3 col-form-label">郵便番号</label>
    <div class="col-4"><%= f.text_field :postal_code, class: "form-control" %></div>
  </div>
  <div class="form-group row">
    <label class="col-3 col-form-label">住所</label>
    <div class="col-9"><%= f.text_field :address, class: "form-control" %></div>
  </div>
  <div class="form-group row">
    <label class="col-3 col-form-label">電話番号</label>
    <div class="col-4"><%= f.text_field :telephone_number, class: "form-control" %></div>
  </div>
  <div class="form-group row">
    <label class="col-3 col-form-label">メールアドレス</label>
    <div class="col-4"><%= f.text_field :email, class: "form-control" %></div>
  </div>
  <div class="form-group row">
    <label class="col-3 col-form-label">会員ステータス</label>
    <div class="col-4">
      <%= f.radio_button :is_active, "有効" %>
      <%= f.label :is_active, "有効" %>
      <%= f.radio_button :is_active, "退会" %>
      <%= f.label :is_active, "退会" %>
    </div>
  </div>
  <div class="row">
    <div class="col-3"></div>
    <div class="col-4">
      <%= f.submit '変更を保存', class: 'btn btn-success' %>
    </div>
  </div>
  <% end %>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row">
    <h4 class="bg-light px-3 my-3">会員一覧</h4>
  </div>
  <div class="row">
    <table class="table">
      <thead class="thead-light">
        <tr>
          <th>会員ID</th>
          <th scope="col">
            氏名
          </th>
          <th scope="col">
            メールアドレス
         </th>
          <th scope="col">
            ステータス
          </th>
        </tr>
      </thead>
      <tbody>
        <% @customers.each do |customer| %>
          <tr>
            <th scope="row"><%= customer.id %></th>
            <td>
              <%= link_to admin_customer_path(customer.id), class: 'text-dark btn-default' do %>
                 <%= customer.first_name %><%= customer.last_name %>
              <% end %>
            </td>
            <td><%= customer.email %></td>
            <td>
              <% if customer.is_active == "有効" %>
                <span class="text-success"><strong><%= customer.is_active %></strong></span>
              <% else %>
                <span class="text-secondary"><strong><%= customer.is_active %></strong></span>
              <% end %>
              </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="row">
    <h4 class="bg-light px-3 my-3"><%= @customer.first_name %><%= @customer.last_name %>さんの会員詳細</h4>
  </div>
  <div class="row">
    <table class="table table-borderless">
      <tr>
        <th>会員ID</th>
        <td><%= @customer.id %></td>
      </tr>
      <tr>
        <th>氏名</th>
        <td><%= @customer.first_name %><%= @customer.last_name %></td>
      </tr>
      <tr>
        <th>フリガナ</th>
        <td><%= @customer.first_name_kana %><%= @customer.last_name_kana %></td>
      </tr>
      <tr>
        <th>郵便番号</th>
        <td><%= @customer.postal_code %></td>
      </tr>
      <tr>
        <th>住所</th>
        <td><%= @customer.address %></td>
      </tr>
      <tr>
        <th>電話番号</th>
        <td><%= @customer.telephone_number %></td>
      </tr>
      <tr>
        <th>メールアドレス</th>
        <td><%= @customer.email %></td>
      </tr>
      <tr>
        <th>会員ステータス</th>
        <td>
          <% if @customer.is_active == "有効" %>
            <span class="text-success"><strong><%= @customer.is_active %></strong></span>
          <% else %>
            <span class="text-secondary"><strong><%= @customer.is_active %></strong></span>
          <% end %>
        </td>
      </tr>
    </table>
  </div>
  <div class="row">
    <div class="col text-right">
      <%= link_to edit_admin_customer_path(@customer.id), class: 'btn btn-success' do %>
        <span>編集する</span>
      <% end %>
    </div>
    <div class="col">
      <%= link_to admin_order_path, class: 'btn btn-primary' do %>
        <span>注文履歴一覧を見る</span>
      <% end %>
    </div>
  </div>
</div>