config/routes.rb
Rails.application.routes.draw do

  root to: "public/homes#top"

  scope module: :public do
   resources :items, only: [:index, :show]
    resource :customers, only: [:edit, :update]
    get "customers/my_page" => "customers#show", as: "customers/show"
    get "customers/confirm_withdraw" => "customers#confirm_withdraw"
    patch "customers/withdraw" => "customers#withdraw"
    delete "cart_items/dastroy_all" => "cart_items#destroy_all"
    resources :cart_items, only: [:create, :index, :update]
    post "orders/confirm" => "orders#confirm"
    get "orders/complete" => "orders#complete"
    resources :orders, only: [:new, :create, :index, :show]
    resources :addresses, only: [:new, :create, :edit, :update, :index]
    resources :genres, only: [:show]
    get '/about' => "homes#about", as: "homes/about"
  end

  namespace :admin do
    get "/" => "homes#top", as: "homes/top"
    resources :items, only: [:new, :create, :edit, :update, :index, :show]
    resources :customers, only: [:index, :show, :edit ,:update]
    resources :orders, only: [:show]
    resources :genres, only: [:new, :create, :edit, :update, :index, :show]
  end

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
  }
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  def address_display
    '〒' + shipping_postal_code + ' ' + shipping_address + ' ' + shipping_name
  end

  validates :shipping_postal_code, presence: true
  validates :shipping_address, presence: true
  validates :shipping_name, presence: true
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item

  def subtotal
    item.with_tax_price * amount
  end

  validates :amount, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :email, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true

  enum is_active: { '有効': true, '退会': false }
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy

  validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  belongs_to :genre

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/default-image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end

  def with_tax_price
    (price*1.1).floor
  end

  validates :name, presence: true
  validates :introduction, presence: true
  validates :image, presence: true
  validates :price, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details, dependent: :destroy
  belongs_to :customer
  enum payment_method: { credit_card: 0, transfer: 1 }

  validates :payment_method, presence: true
  validates :shipping_postal_code, presence: true
  validates :shipping_address, presence: true
  validates :shipping_name, presence: true
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :item
  belongs_to :order
  def with_tax_price
    (price*1.1).floor
  end

  def subtotal
    item.with_tax_price * amount
  end

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

  def create
    genre = Genre.new(genre_params)
    if genre.save
       redirect_to '/admin/genres'
    else
      render :index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    genre = Genre.find(params[:id])
    if genre.update(genre_params)
       redirect_to admin_genres_path
    else
      @genre = Genre.find(params[:id])
      render :edit
    end
  end

  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.page(params[:page]).per(10)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.page(params[:page]).per(10)
  end

  def new
    @item = Item.new
  end

  def create
    item = Item.new(item_params)
    if item.save
       redirect_to admin_item_path(item.id)
    else
      @item = Item.new
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    item = Item.find(params[:id])
    if item.update(item_params)
       redirect_to admin_item_path(item.id)
    else
      @item = Item.find(params[:id])
      render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:image, :name, :introduction,:genre_id, :price)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details.all
    @total = @order_details.inject(0) { |sum, order_detail| sum + order_detail.subtotal}
    @amount_bill = @total + "800".to_i
  end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController

  def after_sign_in_path(resource)
    admin_homes_top_path
  end

  def after_sign_out_pth(resource)
    new_admin_session_path
  end
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  private
def after_sign_in_path_for(resource_or_scope)
    if resource_or_scope.is_a?(Admin)
        admin_homes_top_path
    else
        root_path
    end
end

def
after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :user
        root_path
    elsif resource_or_scope == :admin
        new_admin_session_path
    else
        root_path
    end
end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/admin/genres/edit.html.erb
<div class="container">
  <div class="row">
    <h4 class="bg-light px-3 my-3">ジャンル編集</h4>
  </div>
  <%= form_with model: [:admin, @genre] do |f| %>
  <div class="form-group row my-5">
    <label class="col-2 col-form-label">ジャンル名</label>
    <div class="col-3">
      <%= f.text_field :name %>
    </div>
    <div class="col-3">
      <%= f.submit '編集を保存', class: 'btn btn-success' %>
    </div>
  </div>
  <% end %>
</div>

app/views/admin/genres/index.html.erb
<div class="container">
  <div class="row">
    <h4 class="bg-light px-3 my-3">注文履歴一覧</h4>
  </div>
  <%= form_with model: [:admin ,@genre] do |f| %>
  <div class="form-group row my-5">
    <label class="col-2 col-form-label">ジャンル名</label>
    <div class="col-3">
      <%= f.text_field :name, placeholder: "ジャンル名", class: "form-control" %>
    </div>
    <div class="col-3">
      <%= f.submit '新規登録', class: 'btn btn-success' %>
    </div>
  </div>
  <% end %>
  <div class="row">
    <div class="col-4">
      <table class="table">
        <thead class="thead-light">
          <th class="text-center">ジャンル</th>
          <th></th>
        </thead>
        <% @genres.each do |genre| %>
        <tr>
          <td><%= genre.name %></td>
          <td class="text-center">
            <%= link_to edit_admin_genre_path(genre.id), class: 'btn  btn-success' do %>
              <span>編集する</span>
            <% end %>
          </td>
        </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/admin/items/edit.html.erb
<div class="container">
  <div class="row">
    <h4 class="bg-light px-3 my-3">商品編集</h4>
  </div>
  <%= form_with model: [:admin ,@item] do |f| %>
   <div class="form-group row">
    <label class="col-3 col-form-label">商品画像</label>
    <div class="col-4">
      <%= f.file_field :image, accept: "image/*" %>
    </div>
  </div>
  <div class="form-group row">
    <label class="col-3 col-form-label">商品名</label>
    <div class="col-4">
      <%= f.text_field :name, placeholder: "商品名", class: "form-control" %>
    </div>
  </div>
  <div class="form-group row">
    <label class="col-3 col-form-label">商品説明</label>
    <div class="col-4">
      <%= f.text_area :introduction, placeholder: "ここに説明文を記述します", class: "form-control rows-3" %>
    </div>
  </div>
  <div class="form-group row">
    <label class="col-3 col-form-label">ジャンル</label>
    <div class="col-4">
      <%= f.select :genre_id, options_from_collection_for_select(Genre.all, :id, :name), class: "custom-select" %>
    </div>
  </div>
  <div class="form-group row">
    <label class="col-3 col-form-label">税抜価格</label>
    <div class="col-4">
        <%= f.text_field :price, placeholder: "1000", class: "form-control" %>
    </div>
    <div class="col">
      <span>円</span>
    </div>
  </div>
  <div class="row">
    <div class="col-3"></div>
    <div class="col-4 text-center">
      <%= f.submit '変更を保存', class: "btn btn-success" %>
    </div>
  </div>
  <% end %>
</div>

app/views/admin/items/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-2">
      <h4 class="bg-light text-center px-3 my-3">商品一覧</h4>
    </div>
    <div class="col text-right ">
      <%= link_to new_admin_item_path do %>
        <div class="btn btn-light" style="width: 45px; height: 45px; border-radius: 50%;">
          <p style="font-size: 20px;">+</p>
        </div>
      <% end %>
    </div>
  </div>
  <div class="row">
    <table class="table">
      <thead class="thead-light">
        <tr>
          <th>商品ID</th>
          <th scope="col">
            商品名
          </th>
          <th scope="col">
            税抜き価格
         </th>
          <th scope="col">
            ジャンル
          </th>
        </tr>
      </thead>
      <tbody>
        <% @items.each do |item| %>
          <tr>
            <th scope="row"><%= item.id %></th>
            <td>
              <%= link_to admin_item_path(item.id), class: 'text-dark btn-default' do %>
                <%= item.name %>
              <% end %>
            </td>
            <td><%= item.price %></td>
            <td><%= item.genre.name %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="row">
    <div class="col-6 offset-3 text-center">
      <%= paginate @items %>
    </div>
  </div>
</div>

app/views/admin/items/new.html.erb
<div class="container">
  <div class="row">
    <h4 class="bg-light px-3 my-3">商品新規登録</h4>
  </div>
  <%= form_with model: [:admin ,@item] do |f| %>
  <div class="form-group row">
    <label class="col-3 col-form-label">商品画像</label>
    <div class="col-4">
      <%= f.file_field :image, accept: "image/*" %>
    </div>
  </div>
  <div class="form-group row">
    <label class="col-3 col-form-label">商品名</label>
    <div class="col-4">
      <%= f.text_field :name, placeholder: "商品名", class: "form-control" %>
    </div>
  </div>
  <div class="form-group row">
    <label class="col-3 col-form-label">商品説明</label>
    <div class="col-4">
      <%= f.text_area :introduction, placeholder: "ここに説明文を記述します", class: "form-control rows-3" %>
    </div>
  </div>
  <div class="form-group row">
    <label class="col-3 col-form-label">ジャンル</label>
    <div class="col-4">
      <%= f.select :genre_id, options_from_collection_for_select(Genre.all, :id, :name), class: "custom-select", prompt: "選択してください" %>
    </div>
  </div>
  <div class="form-group row">
    <label class="col-3 col-form-label">税抜価格</label>
    <div class="col-4">
        <%= f.text_field :price, placeholder: "1000", class: "form-control" %>
    </div>
    <div class="col">
      <span>円</span>
    </div>
  </div>
  <div class="row">
    <div class="col-3"></div>
    <div class="col-4 text-center">
      <%= f.submit '新規登録', class: "btn btn-success" %>
    </div>
  </div>
  <% end %>
</div>

app/views/admin/items/show.html.erb
<div class="container">
  <div class="row">
    <h4 class="bg-light px-3 my-3">商品詳細</h4>
  </div>
  <div class="row">
    <div class="col-4">
      <%= image_tag @item.get_image(300,200) %>
    </div>
    <div class="col">
      <table class="table table-lg table-borderless">
        <tr>
          <td>商品名</td>
          <td><%= @item.name %></td>
        </tr>
        <tr>
          <td>商品説明</td>
          <td><%= @item.introduction %></td>
        </tr>
        <tr>
          <td>ジャンル</td>
          <td><%= @item.genre.name %></td>
        </tr>
        <tr>
          <td>税込価格</br>(税抜価格)</td>
          <td>￥<%= @item.with_tax_price.to_s(:delimited) %>（<%= @item.price.to_s(:delimited) %>）円</td>
        </tr>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="col-4"></div>
    <div class="col-5 text-center">
      <%= link_to edit_admin_item_path(@item.id), class: 'btn btn-success' do %>
        <span>編集する</span>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="row">
    <h4 class="bg-light px-3 my-3">注文履歴詳細</h4>
  </div>
  <div class="row">
    <div class="col-6">
      <table class="table table-borderless">
          <tr>
            <th>購入者</th>
            <td>
              <%= link_to admin_customer_path(@order.id), class: 'text-dark  btn-default' do %>
                <%= @order.customer.first_name %>
                <%= @order.customer.last_name %>
              <% end %>
            </td>
          </tr>
          <tr>
            <th>注文日</th>
            <td><%= @order.created_at.strftime('%Y/%m/%d') %></td>
          </tr>
          <tr>
            <th>配送先</th>
            <td>
              <span>〒</span>
              <%= @order.shipping_postal_code %>
              <%= @order.shipping_address %>
              <%= @order.shipping_name %>
            </td>
          </tr>
          <tr>
            <th>支払方法</th>
            <td><%= @order.payment_method_i18n %></td>
          </tr>
        </thead>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="col-5">
      <table class="table table-borderless">
        <thead class="thead-light">
          <th>商品名</th>
          <th>単価（税込）</th>
          <th>数量</th>
          <th>小計</th>
          <% @order_details.each do |order_detail| %>
          <tr>
            <td><%= order_detail.item.name %></td>
            <td><%= order_detail.item.with_tax_price.to_s(:delimited) %></td>
            <td><%= order_detail.amount %></td>
            <td><%= order_detail.subtotal.to_s(:delimited) %></td>
          </tr>
          <% end %>
        </thead>
      </table>
    </div>
    <div class="col-3">
      <table class="table table-borderless">
        <tr>
          <th>商品合計</th>
          <td><%= @total.to_s(:delimited) %></td>
        </tr>
        <tr>
          <th>配送料</th>
          <td><span>800円</span></td>
        </tr>
        <tr>
          <th>ご請求金額</th>
          <td><%= @order.amount_bill.to_s(:delimited) %>円</td>
        </tr>
      </table>
    </div>
  </div>
</div>