config/routes.rb
Rails.application.routes.draw do

  root to: "public/homes#top"

  scope module: :public do
   resources :items, only: [:index, :show]
    resource :customers, only: [:edit, :update]
    get "customers/my_page" => "customers#show", as: "customers/show"
    get "customers/confirm_withdraw" => "customers#confirm_withdraw"
    patch "customers/withdraw" => "customers#withdraw"
    delete "cart_items/dastroy_all" => "cart_items#destroy_all"
    resources :cart_items, only: [:create, :index, :update]
    post "orders/confirm" => "orders#confirm"
    get "orders/complete" => "orders#complete"
    resources :orders, only: [:new, :create, :index, :show]
    resources :addresses, only: [:new, :create, :edit, :update, :index]
    resources :genres, only: [:show]
    get '/about' => "homes#about", as: "homes/about"
  end

  namespace :admin do
    get "/" => "homes#top", as: "homes/top"
    resources :items, only: [:new, :create, :edit, :update, :index, :show]
    resources :customers, only: [:index, :show, :edit ,:update]
    resources :orders, only: [:show]
    resources :genres, only: [:new, :create, :edit, :update, :index, :show]
  end

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
  }
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  def address_display
    '〒' + shipping_postal_code + ' ' + shipping_address + ' ' + shipping_name
  end

  validates :shipping_postal_code, presence: true
  validates :shipping_address, presence: true
  validates :shipping_name, presence: true
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item

  def subtotal
    item.with_tax_price * amount
  end

  validates :amount, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :email, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true

  enum is_active: { '有効': true, '退会': false }
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy

  validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  belongs_to :genre

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/default-image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end

  def with_tax_price
    (price*1.1).floor
  end

  validates :name, presence: true
  validates :introduction, presence: true
  validates :image, presence: true
  validates :price, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details, dependent: :destroy
  belongs_to :customer
  enum payment_method: { credit_card: 0, transfer: 1 }

  validates :payment_method, presence: true
  validates :shipping_postal_code, presence: true
  validates :shipping_address, presence: true
  validates :shipping_name, presence: true
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :item
  belongs_to :order
  def with_tax_price
    (price*1.1).floor
  end

  def subtotal
    item.with_tax_price * amount
  end

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

  def create
    genre = Genre.new(genre_params)
    if genre.save
       redirect_to '/admin/genres'
    else
      render :index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    genre = Genre.find(params[:id])
    if genre.update(genre_params)
       redirect_to admin_genres_path
    else
      @genre = Genre.find(params[:id])
      render :edit
    end
  end

  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.page(params[:page]).per(10)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.page(params[:page]).per(10)
  end

  def new
    @item = Item.new
  end

  def create
    item = Item.new(item_params)
    if item.save
       redirect_to admin_item_path(item.id)
    else
      @item = Item.new
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    item = Item.find(params[:id])
    if item.update(item_params)
       redirect_to admin_item_path(item.id)
    else
      @item = Item.find(params[:id])
      render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:image, :name, :introduction,:genre_id, :price)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  private
def after_sign_in_path_for(resource_or_scope)
    if resource_or_scope.is_a?(Admin)
        admin_homes_top_path
    else
        root_path
    end
end

def
after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :user
        root_path
    elsif resource_or_scope == :admin
        new_admin_session_path
    else
        root_path
    end
end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">
    <header class="shadow-sm mb-5">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
          <a class="navbar-brand" href="/">Nageno Cake</a>
          <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
              <% if admin_signed_in? %>
                <li class="nav-item" style="margin-right: 10px;">
                  <%= link_to admin_items_path, class: 'text-decoration-none text-dark  btn-default' do %>
                    <span>商品一覧</span>
                  <% end %>
                </li>
                <li class="nav-item" style="margin-right: 10px;">
                  <%= link_to admin_customers_path, class: 'text-decoration-none text-dark btn-default' do %>
                    <span>会員一覧</span>
                  <% end %>
                </li>
                <li class="nav-item" style="margin-right: 10px;">
                  <%= link_to admin_homes_top_path, class: 'text-decoration-none text-dark btn-default' do %>
                    <span>注文履歴一覧</span>
                  <% end %>
                </li>
                <li class="nav-item" style="margin-right: 10px;">
                  <%= link_to admin_genres_path, class: 'text-decoration-none text-dark btn-default' do %>
                    <span>ジャンル一覧</span>
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to destroy_admin_session_path, method: :delete, class: 'text-decoration-none text-dark btn-default' do%>
                    <span>ログアウト</span>
                  <% end %>
                </li>

              <% elsif customer_signed_in? %>
                <li class="nav-item" style="margin-right: 10px;">
                  <%= link_to customers_show_path, class: 'text-decoration-none text-dark btn-default' do %>
                    <span>マイページ</span>
                  <% end %>
                </li>
                <li class="nav-item" style="margin-right: 10px;">
                  <%= link_to items_path, class: 'text-decoration-none text-dark btn-default' do %>
                    <span>商品一覧</span>
                  <% end %>
                </li>
                <li class="nav-item" style="margin-right: 10px;">
                  <%= link_to cart_items_path, class: 'text-decoration-none text-dark btn-default' do %>
                    <span>カート</span>
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to destroy_customer_session_path, method: :delete, class: 'text-decoration-none text-dark btn-default' do%>
                    <span>ログアウト</span>
                  <% end %>
                </li>

              <% else %>
                <li class="nav-item" style="margin-right: 10px;">
                  <%= link_to homes_about_path, class: 'text-decoration-none text-dark btn-default' do %>
                    <span>About</span>
                  <% end %>
                </li>
                <li class="nav-item" style="margin-right: 10px;">
                  <%= link_to items_path, class: 'text-decoration-none text-dark btn-default' do %>
                    <span>商品一覧</span>
                  <% end %>
                </li>
                <li class="nav-item" style="margin-right: 10px;">
                  <%= link_to new_customer_registration_path, class: 'text-decoration-none text-dark btn-default' do %>
                    <span>新規登録</span>
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to new_customer_session_path, class: 'text-decoration-none text-dark btn-default' do %>
                    <span>ログイン</span>
                  <% end %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <%= yield %>
  </body>
</html>